# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listAndReitings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 529)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabLists = QtWidgets.QWidget()
        self.tabLists.setObjectName("tabLists")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tabLists)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.tabLists)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.spinBoxLevelAdd = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxLevelAdd.setObjectName("spinBoxLevelAdd")
        self.verticalLayout_9.addWidget(self.spinBoxLevelAdd)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.pushButtonAdd = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.verticalLayout_10.addWidget(self.pushButtonAdd)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_12.addLayout(self.horizontalLayout)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabLists)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.comboBoxChangeEmpl = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxChangeEmpl.setObjectName("comboBoxChangeEmpl")
        self.verticalLayout_2.addWidget(self.comboBoxChangeEmpl)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.spinBoxLevelChange = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxLevelChange.setObjectName("spinBoxLevelChange")
        self.verticalLayout_4.addWidget(self.spinBoxLevelChange)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.pushButtonChange = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonChange.setObjectName("pushButtonChange")
        self.verticalLayout_5.addWidget(self.pushButtonChange)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabLists)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.comboBoxDellEmpl = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxDellEmpl.setObjectName("comboBoxDellEmpl")
        self.verticalLayout_3.addWidget(self.comboBoxDellEmpl)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.pushButtonDellOne = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonDellOne.setObjectName("pushButtonDellOne")
        self.verticalLayout_6.addWidget(self.pushButtonDellOne)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.pushButtonDellAll = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonDellAll.setObjectName("pushButtonDellAll")
        self.verticalLayout_7.addWidget(self.pushButtonDellAll)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tabLists, "")
        self.tabReitings = QtWidgets.QWidget()
        self.tabReitings.setObjectName("tabReitings")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tabReitings)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.spinBoxYear = QtWidgets.QSpinBox(self.tabReitings)
        self.spinBoxYear.setBaseSize(QtCore.QSize(25, 0))
        self.spinBoxYear.setMinimum(1990)
        self.spinBoxYear.setMaximum(3000)
        self.spinBoxYear.setObjectName("spinBoxYear")
        self.horizontalLayout_4.addWidget(self.spinBoxYear)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabReitings)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.graphicsViewReiting = QtWidgets.QGraphicsView(self.groupBox_4)
        self.graphicsViewReiting.setObjectName("graphicsViewReiting")
        self.verticalLayout_14.addWidget(self.graphicsViewReiting)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonCalcCoef = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonCalcCoef.setObjectName("pushButtonCalcCoef")
        self.horizontalLayout_5.addWidget(self.pushButtonCalcCoef)
        self.pushButtonRepeat = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonRepeat.setObjectName("pushButtonRepeat")
        self.horizontalLayout_5.addWidget(self.pushButtonRepeat)
        self.pushButtonSaveCoef = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonSaveCoef.setObjectName("pushButtonSaveCoef")
        self.horizontalLayout_5.addWidget(self.pushButtonSaveCoef)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.verticalLayout_13.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabReitings)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_15.addWidget(self.tableWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.pushButtonCalcReite = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButtonCalcReite.setObjectName("pushButtonCalcReite")
        self.horizontalLayout_6.addWidget(self.pushButtonCalcReite)
        self.pushButtonSaveReit = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButtonSaveReit.setObjectName("pushButtonSaveReit")
        self.horizontalLayout_6.addWidget(self.pushButtonSaveReit)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.verticalLayout_13.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tabReitings, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Списки и Рейтинги"))
        self.groupBox.setTitle(_translate("Dialog", "Добавление"))
        self.label_4.setText(_translate("Dialog", "Сотрудник"))
        self.label_5.setText(_translate("Dialog", "Приоритет"))
        self.pushButtonAdd.setText(_translate("Dialog", "Добавить"))
        self.label_6.setText(_translate("Dialog", "Приоритет в рейтинге:\n"
"0 -  нет приоритета\n"
"1 -  выбирает до 0 уровня\n"
"2 - выбирает все отпуска сразу после высших приоритетов\n"
"3 - и т.д."))
        self.groupBox_2.setTitle(_translate("Dialog", "Изменение"))
        self.label.setText(_translate("Dialog", "Сотрудник"))
        self.label_3.setText(_translate("Dialog", "Приоритет"))
        self.pushButtonChange.setText(_translate("Dialog", "Изменить"))
        self.groupBox_3.setTitle(_translate("Dialog", "Удаление"))
        self.label_2.setText(_translate("Dialog", "Сотрудник"))
        self.pushButtonDellOne.setText(_translate("Dialog", "Удалить"))
        self.pushButtonDellAll.setText(_translate("Dialog", "Удалить всех"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLists), _translate("Dialog", "Списки"))
        self.groupBox_4.setTitle(_translate("Dialog", "Коэфециенты"))
        self.pushButtonCalcCoef.setText(_translate("Dialog", "Рассчитать"))
        self.pushButtonRepeat.setText(_translate("Dialog", "Повторить"))
        self.pushButtonSaveCoef.setText(_translate("Dialog", "Сохранить"))
        self.groupBox_5.setTitle(_translate("Dialog", "Рейтинги сотрудников"))
        self.pushButtonCalcReite.setText(_translate("Dialog", "Рассчитать"))
        self.pushButtonSaveReit.setText(_translate("Dialog", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReitings), _translate("Dialog", "Рейтинги"))

