# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NCMatrix.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormNCMatrix(object):
    def setupUi(self, FormNCMatrix):
        FormNCMatrix.setObjectName("FormNCMatrix")
        FormNCMatrix.setWindowModality(QtCore.Qt.ApplicationModal)
        FormNCMatrix.resize(689, 478)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormNCMatrix)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidgetNCM = QtWidgets.QTableWidget(FormNCMatrix)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tableWidgetNCM.setFont(font)
        self.tableWidgetNCM.setObjectName("tableWidgetNCM")
        self.tableWidgetNCM.setColumnCount(0)
        self.tableWidgetNCM.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidgetNCM)
        self.groupBox = QtWidgets.QGroupBox(FormNCMatrix)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEditNewRule = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditNewRule.setObjectName("lineEditNewRule")
        self.verticalLayout_6.addWidget(self.lineEditNewRule)
        self.horizontalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEditShorty = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEditShorty.setBaseSize(QtCore.QSize(20, 0))
        self.lineEditShorty.setObjectName("lineEditShorty")
        self.verticalLayout_7.addWidget(self.lineEditShorty)
        self.horizontalLayout_8.addWidget(self.groupBox_6)
        self.pushButtonCreateNewRule = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonCreateNewRule.setObjectName("pushButtonCreateNewRule")
        self.horizontalLayout_8.addWidget(self.pushButtonCreateNewRule)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBoxFirstEmployee = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxFirstEmployee.setObjectName("comboBoxFirstEmployee")
        self.verticalLayout_2.addWidget(self.comboBoxFirstEmployee)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBoxSecondEmployee = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxSecondEmployee.setObjectName("comboBoxSecondEmployee")
        self.verticalLayout_3.addWidget(self.comboBoxSecondEmployee)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBoxRule = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBoxRule.setObjectName("comboBoxRule")
        self.verticalLayout_4.addWidget(self.comboBoxRule)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonApplyRule = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonApplyRule.setObjectName("pushButtonApplyRule")
        self.horizontalLayout.addWidget(self.pushButtonApplyRule)
        self.pushButtonCancelRule = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonCancelRule.setObjectName("pushButtonCancelRule")
        self.horizontalLayout.addWidget(self.pushButtonCancelRule)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(FormNCMatrix)
        QtCore.QMetaObject.connectSlotsByName(FormNCMatrix)

    def retranslateUi(self, FormNCMatrix):
        _translate = QtCore.QCoreApplication.translate
        FormNCMatrix.setWindowTitle(_translate("FormNCMatrix", "Матрица непересечений"))
        self.groupBox.setTitle(_translate("FormNCMatrix", "Создать правило"))
        self.groupBox_5.setTitle(_translate("FormNCMatrix", "Правило"))
        self.groupBox_6.setTitle(_translate("FormNCMatrix", "Обозначение"))
        self.pushButtonCreateNewRule.setText(_translate("FormNCMatrix", "Добавить новое правило"))
        self.groupBox_2.setTitle(_translate("FormNCMatrix", "Сотрудник"))
        self.groupBox_3.setTitle(_translate("FormNCMatrix", "Сотруник"))
        self.groupBox_4.setTitle(_translate("FormNCMatrix", "Правило"))
        self.pushButtonApplyRule.setText(_translate("FormNCMatrix", "Применить правило"))
        self.pushButtonCancelRule.setText(_translate("FormNCMatrix", "Отменить правило"))

