# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertysUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(468, 299)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalSliderPercent = QtWidgets.QSlider(Form)
        self.horizontalSliderPercent.setMaximum(100)
        self.horizontalSliderPercent.setSliderPosition(20)
        self.horizontalSliderPercent.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPercent.setObjectName("horizontalSliderPercent")
        self.horizontalLayout.addWidget(self.horizontalSliderPercent)
        self.lcdNumberPercent = QtWidgets.QLCDNumber(Form)
        self.lcdNumberPercent.setObjectName("lcdNumberPercent")
        self.horizontalLayout.addWidget(self.lcdNumberPercent)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalSliderManagerPercent = QtWidgets.QSlider(Form)
        self.horizontalSliderManagerPercent.setMaximum(100)
        self.horizontalSliderManagerPercent.setSliderPosition(8)
        self.horizontalSliderManagerPercent.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderManagerPercent.setObjectName("horizontalSliderManagerPercent")
        self.horizontalLayout_2.addWidget(self.horizontalSliderManagerPercent)
        self.lcdNumberManagerPercent = QtWidgets.QLCDNumber(Form)
        self.lcdNumberManagerPercent.setObjectName("lcdNumberManagerPercent")
        self.horizontalLayout_2.addWidget(self.lcdNumberManagerPercent)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.checkBoxNCMatrix = QtWidgets.QCheckBox(Form)
        self.checkBoxNCMatrix.setObjectName("checkBoxNCMatrix")
        self.verticalLayout_3.addWidget(self.checkBoxNCMatrix)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxPercentInMonth = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxPercentInMonth.setObjectName("checkBoxPercentInMonth")
        self.verticalLayout.addWidget(self.checkBoxPercentInMonth)
        self.checkBoxPercent = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxPercent.setObjectName("checkBoxPercent")
        self.verticalLayout.addWidget(self.checkBoxPercent)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxPercentManagerInMonth = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxPercentManagerInMonth.setObjectName("checkBoxPercentManagerInMonth")
        self.verticalLayout_2.addWidget(self.checkBoxPercentManagerInMonth)
        self.checkBoxPercentManager = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxPercentManager.setObjectName("checkBoxPercentManager")
        self.verticalLayout_2.addWidget(self.checkBoxPercentManager)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonOk = QtWidgets.QPushButton(Form)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout_3.addWidget(self.pushButtonOk)
        self.pushButtonCancel = QtWidgets.QPushButton(Form)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_3.addWidget(self.pushButtonCancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки"))
        self.label.setText(_translate("Form", "Процент сотрудников в отпуске одновременно"))
        self.label_2.setText(_translate("Form", "Процент руководителей в отпуске одновременно"))
        self.checkBoxNCMatrix.setText(_translate("Form", "Использовать матрицу непересечений"))
        self.groupBox.setTitle(_translate("Form", "Сотрудники"))
        self.checkBoxPercentInMonth.setText(_translate("Form", "Учитывать процент отдыхающих в месяц"))
        self.checkBoxPercent.setText(_translate("Form", "Запрещать выбор отпуска при превышении отдыхающих одновременно "))
        self.groupBox_2.setTitle(_translate("Form", "Руководители"))
        self.checkBoxPercentManagerInMonth.setText(_translate("Form", "Учитывать процент руководителей отдыхающих в месяц"))
        self.checkBoxPercentManager.setText(_translate("Form", "Запрещать выбор отпуска при превышении отдыхающих одновременно "))
        self.pushButtonOk.setText(_translate("Form", "Ok"))
        self.pushButtonCancel.setText(_translate("Form", "Отмена"))

